// AUTH TYPES
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const SET_PERMISSIONS = "SET_PERMISSIONS";


//LOADER
export const LOADER_ON = 'LOADER_ON';
export const LOADER_OFF = 'LOADER_OFF';


// ledger section
export const UPDATE_LEDGER_GROUP_FORM_FIELD = 'UPDATE_LEDGER_GROUP_FORM_FIELD';
export const RESET_LEDGER_GROUP_FORM = 'RESET_LEDGER_GROUP_FORM';
export const LEDGER_GROUPS_LOADED = 'LEDGER_GROUPS_LOADED';
export const LEDGER_GROUP_BY_ID_LOADED = 'LEDGER_GROUP_BY_ID_LOADED';
export const UNDER_GROUPS_LOADED = 'UNDER_GROUPS_LOADED';
export const UNDER_GROUPS_CLEAR = 'UNDER_GROUPS_CLEAR';
export const UPDATE_FORM_FIELD_TYPE = 'UPDATE_FORM_FIELD_TYPE';

export const SET_LEDGER_TREE = 'SET_LEDGER_TREE';
export const ADD_LEDGER_CHILDREN = 'ADD_LEDGER_CHILDREN';
export const SET_LOADING_NODE = 'SET_LOADING_NODE';