name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_DEV_USER }}
          key: ${{ secrets.EC2_DEV_KEY }}
          port: ${{ secrets.EC2_DEV_PORT }}
          script: |
            cd al_sabeel_web/

            echo "Resetting codebase..."
            git reset --hard
            git clean -fd
            git checkout dev
            git pull origin dev

            echo "Installing dependencies..."
            npm install

            echo "Building the React app..."
            npm run build

            echo "Restarting static server on port 3010..."
            pkill -f "serve" || true
            nohup npx serve -s build -l 3010 > serve.log 2>&1 &

