# name: Deploy windson-app to Dev EC2 using Docker Compose

# on:
#   push:
#     branches:
#       - prod

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     name: Build & Deploy to Dev

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_REGION }}

#     - name: Login to Amazon ECR
#       run: |
#         aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
#         docker login --username AWS \
#         --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

#     - name: Build & tag image using docker-compose
#       run: |
#         docker compose -f docker-compose.dev.yml build
#         docker tag windson-dev ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/windson-app:dev

#     - name: Push image to ECR
#       run: |
#         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/windson-app:dev

#     - name: Deploy to Dev EC2
#       uses: appleboy/ssh-action@v0.1.5
#       with:
#         host: ${{ secrets.DEV_EC2_HOST }}
#         username: ${{ secrets.DEV_EC2_USER }}
#         key: ${{ secrets.DEV_EC2_KEY }}
#         port: ${{ secrets.DEV_EC2_PORT }}
#         script: refresh-docker-compose
